## Q1. Interchange row and column

In [1]:
import numpy as np

In [3]:
np.random.seed(0)

arr = np.array(np.random.randint(1, 101,(3,3)))
print(arr)

[[45 48 65]
 [68 68 10]
 [84 22 37]]


In [4]:
arr_trans = np.transpose(arr)
print(arr_trans)

[[45 68 84]
 [48 68 22]
 [65 10 37]]


## Reshape 1D array

In [6]:
np.random.seed(10)

arr = np.array(np.random.randint(1, 101,10))
print(arr)

[10 16 65 29 90 94 30  9 74  1]


In [9]:
arr_reshape_2x5 = arr.reshape(2,5)
print(arr_reshape_2x5)

[[10 16 65 29 90]
 [94 30  9 74  1]]


In [10]:
arr_reshape_5x2 = arr.reshape(5,2)
print(arr_reshape_5x2)

[[10 16]
 [65 29]
 [90 94]
 [30  9]
 [74  1]]


## 4X4 Array with random Float values & 6X6 having zeroes border

In [12]:
np.random.seed(20)

arr_4X4 = np.array(np.random.rand(4,4))
print(arr_4X4)

[[0.5881308  0.89771373 0.89153073 0.81583748]
 [0.03588959 0.69175758 0.37868094 0.51851095]
 [0.65795147 0.19385022 0.2723164  0.71860593]
 [0.78300361 0.85032764 0.77524489 0.03666431]]


In [13]:
arr_6X6 = np.pad(arr_4X4,((1,1),(1,1)),'constant',constant_values=0)
print(arr_6X6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5881308  0.89771373 0.89153073 0.81583748 0.        ]
 [0.         0.03588959 0.69175758 0.37868094 0.51851095 0.        ]
 [0.         0.65795147 0.19385022 0.2723164  0.71860593 0.        ]
 [0.         0.78300361 0.85032764 0.77524489 0.03666431 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## Q4. Array of Integers from 10 to 60 with step of 5

In [14]:
arr = np.arange(10,61,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


## Q5. Case Transformation

In [15]:
arr = np.array(['python', 'numpy', 'pandas'])
print(arr)

['python' 'numpy' 'pandas']


In [17]:
uppercase = np.char.upper(arr)
print(uppercase)
lowercase = np.char.lower(arr)
print(lowercase)
titlecase = np.char.title(arr)
print(titlecase)
swapcase = np.char.swapcase(arr)
print(swapcase)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']
['PYTHON' 'NUMPY' 'PANDAS']


## Q6. Insert space between each character

In [18]:
words = np.array(['hello','world','python','numpy','pandas'])
print(words)

spaced_words = np.char.join(' ',words)
print(spaced_words)

['hello' 'world' 'python' 'numpy' 'pandas']
['h e l l o' 'w o r l d' 'p y t h o n' 'n u m p y' 'p a n d a s']


## Q7. Element wise operation on 2D Numpy Array

In [19]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [20]:
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

In [22]:
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nAddition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Q8. Extracting Diagonal Matrix

In [23]:
identity_matrix = np.identity(5)
print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Diagonal Elements:
[1. 1. 1. 1. 1.]


## Q9. Prime numbers in an array

In [25]:
np.random.seed(30)
random_array = np.random.randint(0, 1001, 100)
print("Random Array:")
print(random_array)

Random Array:
[805 421 941 813 500 140 919 898 821 763 145 430 131 425 263 887 833 689
 941 445 163 530  18 116 358 460 912 390  62 283  46 173 320 574 267 527
 919 484 781 946 673 567 668 625 186 859 846 441 104 843  95 172 933 203
 697 807 649 161 888 943 423 420 278 680 665 438 240 631 837 105 218 922
 206 859 531 414 561 989  52 556 189 546 491 975 811 284 444 716 435 169
 696 528  39 289 265 523 476 772 866 412]


In [26]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

In [27]:
prime_numbers = random_array[np.vectorize(is_prime)(random_array)]

print("\nPrime Numbers:")
print(prime_numbers)


Prime Numbers:
[421 941 919 821 131 263 887 941 163 283 173 919 673 859 631 859 491 811
 523]


## Q10. Numpy array representing Daily Temperature for a month. Displaying it's average

In [40]:
np.random.seed(50)
daily_temperatures = np.random.randint(50, 90, 30)
print("Daily Temperatures:")
print(daily_temperatures)

Daily Temperatures:
[82 61 83 80 54 56 87 56 72 55 52 81 57 54 64 85 78 77 76 76 56 70 81 71
 50 56 69 52 65 80]


In [41]:
daily_temperatures_updated = daily_temperatures[:-2]
print("\nUpdated Daily Temperatures:")
print(daily_temperatures_updated)
weekly_temperatures = daily_temperatures_updated.reshape(4, 7)
print("\nWeekly Temperatures:")
print(weekly_temperatures)


Updated Daily Temperatures:
[82 61 83 80 54 56 87 56 72 55 52 81 57 54 64 85 78 77 76 76 56 70 81 71
 50 56 69 52]

Weekly Temperatures:
[[82 61 83 80 54 56 87]
 [56 72 55 52 81 57 54]
 [64 85 78 77 76 76 56]
 [70 81 71 50 56 69 52]]


In [42]:
weekly_average_temperatures = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Average Temperatures:")
print(weekly_average_temperatures)


Weekly Average Temperatures:
[71.85714286 61.         73.14285714 64.14285714]
